# Generated by Django 6.1 on 2026-09-04 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_staffprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ['-created_at']},
        ),
    ]
