# Generated by Django 6.1 on 2026-09-04 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_staffprofile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['is_active'], name='users_clien_is_acti_e6d05c_idx'),
        ),
    ]
