"""
Django settings for homezup project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import sys

from decouple import Csv, config
from django.core.exceptions import ImproperlyConfigured

from homezup.checks import DEV_SECRET, cache_settings, debug_default, production_misconfigurations
from homezup.database import build_databases
from homezup.origins import merge_frontend_origin, railway_runtime_hosts, uses_cross_site_cookies

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TESTING = "test" in sys.argv

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

SECRET_KEY = (config("DJANGO_SECRET_KEY", default=DEV_SECRET) or "").strip().strip('"').strip("'")
ON_RAILWAY = bool(config("RAILWAY_ENVIRONMENT", default=""))
DEBUG = config("DJANGO_DEBUG", default=debug_default(ON_RAILWAY), cast=bool)
ALLOWED_HOSTS = list(
    config(
        "DJANGO_ALLOWED_HOSTS",
        default="127.0.0.1,localhost,testserver",
        cast=Csv(),
    )
)
if ON_RAILWAY:
    for _host in railway_runtime_hosts(
        config("RAILWAY_PUBLIC_DOMAIN", default=""),
        config("RAILWAY_PRIVATE_DOMAIN", default=""),
    ):
        if _host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_host)

FRONTEND_ORIGIN = config(
    "DJANGO_FRONTEND_ORIGIN",
    default="https://system-management.up.railway.app" if ON_RAILWAY else "",
)
# Migrate the previous Railway SPA hostname if still set in service variables.
if (FRONTEND_ORIGIN or "").rstrip("/") == "https://system-management-production-5616.up.railway.app":
    FRONTEND_ORIGIN = "https://system-management.up.railway.app"
# Production SPA host(s). Merged into CORS/CSRF/hosts even when an older
# DJANGO_FRONTEND_ORIGIN is still set on the Railway service.
_RAILWAY_SPA_ORIGINS = (
    "https://system-management.up.railway.app",
)
ALLOWED_HOSTS, _ = merge_frontend_origin(ALLOWED_HOSTS, [], FRONTEND_ORIGIN)
if ON_RAILWAY:
    for _spa in _RAILWAY_SPA_ORIGINS:
        ALLOWED_HOSTS, _ = merge_frontend_origin(ALLOWED_HOSTS, [], _spa)
_production_errors = production_misconfigurations(DEBUG, SECRET_KEY, ALLOWED_HOSTS, TESTING)
if _production_errors:
    raise ImproperlyConfigured(" ".join(_production_errors))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'corsheaders',
    'rest_framework',
    'django_filters',
    'ninja',
    'ninja_extra',
    
    # Local apps
    'core.apps.CoreConfig',
    'users.apps.UsersConfig',
    'bookings.apps.BookingsConfig',
    'fitness.apps.FitnessConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.RequestLogMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'core.middleware.EnsureCsrfCookieMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'homezup.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'homezup.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
# Local / tests: SQLite. Railway: set DATABASE_URL=${{Postgres.DATABASE_URL}}

DATABASES = build_databases(
    BASE_DIR,
    testing=TESTING,
    on_railway=ON_RAILWAY,
    database_url=config("DATABASE_URL", default=""),
    private_url=config("DATABASE_PRIVATE_URL", default=""),
    public_url=config("DATABASE_PUBLIC_URL", default=""),
    pg_name=config("PGDATABASE", default=""),
    pg_user=config("PGUSER", default=""),
    pg_password=config("PGPASSWORD", default=""),
    pg_host=config("PGHOST", default=""),
    pg_port=config("PGPORT", default="5432"),
    test_database_url=config("HOMEZUP_TEST_DATABASE_URL", default=""),
)

CACHES = cache_settings(TESTING, DEBUG)


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

if TESTING:
    # Django docs: faster hasher in tests only. Production keeps PBKDF2/Argon2.
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.MD5PasswordHasher',
    ]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Casablanca'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
WHITENOISE_USE_FINDERS = DEBUG or TESTING
WHITENOISE_AUTOREFRESH = DEBUG
if not DEBUG and not TESTING:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
        },
    }


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = list(
    config(
        "DJANGO_CORS_ORIGINS",
        default="http://localhost:3000,http://localhost:8000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:8000,http://127.0.0.1:5173",
        cast=Csv(),
    )
)
if ON_RAILWAY:
    _railway_domain = config("RAILWAY_PUBLIC_DOMAIN", default="")
    if _railway_domain:
        _origin = f"https://{_railway_domain}"
        if _origin not in CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS.append(_origin)

ALLOWED_HOSTS, CORS_ALLOWED_ORIGINS = merge_frontend_origin(
    ALLOWED_HOSTS,
    CORS_ALLOWED_ORIGINS,
    FRONTEND_ORIGIN,
)
if ON_RAILWAY:
    for _spa in _RAILWAY_SPA_ORIGINS:
        ALLOWED_HOSTS, CORS_ALLOWED_ORIGINS = merge_frontend_origin(
            ALLOWED_HOSTS,
            CORS_ALLOWED_ORIGINS,
            _spa,
        )

CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ['Content-Disposition']

CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)

USE_HTTPS = config("DJANGO_HTTPS", default=ON_RAILWAY, cast=bool)
if USE_HTTPS:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Railway (and most PaaS) terminate TLS. Redirecting HTTP→HTTPS here
    # breaks platform healthchecks that hit http://0.0.0.0:$PORT.
    SECURE_SSL_REDIRECT = config("DJANGO_SSL_REDIRECT", default=False, cast=bool)

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "same-origin"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = False
if USE_HTTPS and uses_cross_site_cookies(
    FRONTEND_ORIGIN,
    config("RAILWAY_PUBLIC_DOMAIN", default=""),
):
    SESSION_COOKIE_SAMESITE = "None"
    CSRF_COOKIE_SAMESITE = "None"

LOG_DIR = BASE_DIR / "logs"
try:
    LOG_DIR.mkdir(exist_ok=True)
    _log_file_ok = True
except OSError:
    _log_file_ok = False
_log_handlers = ["console"]
_handlers = {
    "console": {
        "class": "logging.StreamHandler",
        "formatter": "standard",
    },
}
if _log_file_ok:
    _log_handlers = ["console", "file"]
    _handlers["file"] = {
        "class": "logging.handlers.RotatingFileHandler",
        "filename": LOG_DIR / "flexoper.log",
        "maxBytes": 2_000_000,
        "backupCount": 5,
        "encoding": "utf-8",
        "formatter": "standard",
    }
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": _handlers,
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": _log_handlers,
            "level": "INFO",
            "propagate": False,
        },
        "django.security": {
            "handlers": _log_handlers,
            "level": "WARNING",
            "propagate": False,
        },
        "gunicorn": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "gunicorn.error": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "flexoper.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# This backend is API-only. Set DJANGO_SERVE_FRONTEND=True to serve a built React app.
FRONTEND_DIST = BASE_DIR / "frontend" / "dist"
SERVE_FRONTEND = config("DJANGO_SERVE_FRONTEND", default=False, cast=bool)

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Currency and localization
CURRENCY = 'MAD'
DECIMAL_PLACES = 2

# Backup configuration
BACKUP_DIR = BASE_DIR / 'backups'

# Static files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
