# Generated by Django 6.1 on 2026-09-02 14:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('class_type', models.CharField(choices=[('boxing', 'Boxing'), ('musculation', 'Musculation'), ('aerobic', 'Aerobic'), ('kick_boxing', 'Kick Boxing')], max_length=30)),
                ('price_per_member', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Monthly price per team member in MAD (DH).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['class_type', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'class_type'), name='unique_fitness_class_name_and_type')],
            },
        ),
        migrations.CreateModel(
            name='ClassMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fitness_memberships', to='users.clientprofile')),
                ('training_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='fitness.trainingclass')),
            ],
            options={
                'ordering': ['client__user__first_name', 'client__user__last_name'],
                'constraints': [models.UniqueConstraint(fields=('training_class', 'client'), name='unique_client_per_fitness_class')],
            },
        ),
    ]
