# Generated by Django 6.1 on 2026-09-03 22:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_membership_payment_status_override'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gymnotificationsettings',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AddField(
            model_name='trainer',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Pay per hour in MAD (DH).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.CreateModel(
            name='TrainerPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('hours_worked', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('pay_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='fitness.trainer')),
            ],
            options={
                'ordering': ['-year', '-month', 'trainer__first_name'],
                'constraints': [models.UniqueConstraint(fields=('trainer', 'year', 'month'), name='unique_trainer_payroll_month')],
            },
        ),
    ]
