# Generated by Django 6.1 on 2026-09-03 22:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_trainer_payroll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='hourly_rate',
            new_name='monthly_pay',
        ),
        migrations.AlterField(
            model_name='trainer',
            name='monthly_pay',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Monthly pay in MAD (DH).',
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
            ),
        ),
    ]
