# Generated by Django 6.1 on 2026-09-03 23:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_trainer_monthly_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('electricity', 'Electricity'), ('water', 'Water'), ('internet', 'Internet'), ('rent', 'Rent'), ('cleaning', 'Cleaning'), ('supplies', 'Supplies'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-year', '-month', 'category', '-created_at'],
            },
        ),
    ]
