# Generated by Django 6.1 on 2026-09-03 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_gymexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymWhatsAppReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=40)),
                ('message', models.TextField(blank=True)),
                ('sent_by', models.CharField(blank=True, max_length=160)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_reminders', to='fitness.membership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
