# Generated by Django 6.1 on 2026-09-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_gymwhatsappreminder'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gympayment',
            index=models.Index(fields=['membership', 'status'], name='fitness_gym_members_1b41b5_idx'),
        ),
        migrations.AddIndex(
            model_name='gympayment',
            index=models.Index(fields=['received_at'], name='fitness_gym_receive_57a0ae_idx'),
        ),
    ]
