# Generated by Django 6.1 on 2026-09-05 23:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_scale_list_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=150)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Optional maximum places for this slot. Separate from class roster size.', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_schedules', to='fitness.trainer')),
                ('training_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='fitness.trainingclass')),
            ],
            options={
                'ordering': ['weekday', 'start_time', 'training_class__name'],
                'indexes': [models.Index(fields=['weekday', 'is_active'], name='fitness_cla_weekday_c9e0a6_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='class_schedule_end_after_start')],
            },
        ),
    ]
