# Generated by Django 6.1

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def fill_receipt_numbers(apps, schema_editor):
    BookingPayment = apps.get_model("bookings", "BookingPayment")
    for payment in BookingPayment.objects.filter(receipt_number=""):
        payment.receipt_number = f"HZ-MIGRATED-{payment.id}"
        payment.save(update_fields=["receipt_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(fill_receipt_numbers, migrations.RunPython.noop),
        migrations.AddField(
            model_name="bookingpayment",
            name="received_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_booking_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash")], default="cash", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="bookingpayment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash")], default="cash", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="bookingpayment",
            name="receipt_number",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["provider", "status"],
                name="bookings_bo_provide_status_idx",
            ),
        ),
    ]
